# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

parameters: # aqui van los parametros de configuracion que se usaran en los servicios
  app.mail.from_email: '%env(APP_MAIL_FROM_EMAIL)%'
  app.mail.from_name:  '%env(APP_MAIL_FROM_NAME)%'
  app.mail.support:    '%env(APP_MAIL_SUPPORT)%'
  app.app_name:        '%env(APP_NAME)%'
  app.login_url:       '%env(APP_LOGIN_URL)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # inyecta automáticamente dependencias según el tipo de dato.
    autoconfigure: true # registra automáticamente servicios especiales (commands, event listeners, etc.).

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Service\WelcomeMailer:
    arguments: #Parámetros que Symfony inyectará al crear el servicio WelcomeMailer
      $fromEmail: '%app.mail.from_email%'   #este campo es el que envia los correos
      $fromName:  '%app.mail.from_name%'    # este campo es el nombre que aparece en el correo
      $soporteEmail: '%app.mail.support%'   # Correo de soporte al que los usuarios pueden responder en caso de dudas
      $appName: '%app.app_name%'            # este campo es el nombre de la aplicacion
      $loginUrl: '%app.login_url%'          # este campo es la url de inicio de sesion

  App\Service\RecuperarPasswordMailer:
    arguments: #Parámetros que Symfony inyectará al crear el servicio WelcomeMailer
      $fromEmail: '%app.mail.from_email%'   #este campo es el que envia los correos
      $fromName:  '%app.mail.from_name%'    # este campo es el nombre que aparece en el correo
      $soporteEmail: '%app.mail.support%'   # Correo de soporte al que los usuarios pueden responder en caso de dudas
      $appName: '%app.app_name%'            # este campo es el nombre de la aplicacion
      $loginUrl: '%app.login_url%'          # este campo es la url de inicio de sesion